version: "3.3"

services:

  # ============== [Common] ==============

  real_chatter:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/
      - ./output:/app/output
    command: gunicorn -b '0.0.0.0:8000' -w 4 'main:app' -t 180
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=api.gwizd.justcheckinghow.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=api.gwizd.justcheckinghow.com
    container_name: real_chatter
    restart: always

  frontend:
    build: ./whistleblower
    command: yarn vite --host 0.0.0.0
    ports:
      - "5173:5173"
    environment:
      - VIRTUAL_HOST=gwizd.justcheckinghow.com
      - VIRTUAL_PORT=5173
      - LETSENCRYPT_HOST=gwizd.justcheckinghow.com
    # volumes:
    #   - ./whistleblower:/app

  postgres-chatter:
    image: postgres:15.1
    container_name: postgres_chatter
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_chatter_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_chatter_data:

networks:
  default:
    name: access-your-heart_default
    external: true
